# Generated by Django 4.2.20 on 2025-04-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sight',
            options={'managed': False},
        ),
    ]
